### ISSUE TITLE
generate_terahedron.pyをターミナルから実行できるように環境構築する

### ISSUE THREAD

**Issue by k1105** [k1105/generate_tetrahedron#8]
### TODO
- [x] requirement.txtに必要なライブラリを記述
- [x] READMEに実行手順を追記
- [x] generate_tetrahedronを実行した時に、生成する四面体の個数とマージさせるときのthresholdについてユーザからの入力を受け付ける
- [x] 処理が完了したら、stl形式で書き出してout/{timestamp}/{timestamp}_tetrahedron.stlで書き出し
- [x] 同時に、四面体のグラフをout/{timestamp}/{timestamp}_graph.png
